### ISSUE TITLE
Вывод только городов

### ISSUE THREAD

**Issue by alexsoin** [Stanislavsky69/vue_dadata_3#13]
Как сделать фильтрацию вывода только городов? По типу как [тут](https://codepen.io/dadata/pen/dyWpNM?editors=101). 

Пролистал доку, нашёл только опцию `debounceOptions`, но и как ей пользоваться непонятно, что туда не передаю, форма вообще не реагирует. 

Пробовал передавать в debounceOptions:

```json
{
  "from_bound": { "value": "city" },
  "to_bound": { "value": "city" }
}
```

**Comment by Stanislavsky69** [comment]
Приветствую! Можете попробовать через слоты оставить только город и повесить клик на конкретный элемент выпадающего списка, чтобы подставлять только город.

**Comment by alexsoin** [comment]
В итоге я сделал через другой пакет, [vue-dadata](https://www.npmjs.com/package/vue-dadata). 

Там такое реализуется двумя атрибутами:

```vue
<vue-dadata
  v-model="nameModel"
  :token="tokenDaData"
  from-bound="city"
  to-bound="city"
/>
```
