### ISSUE TITLE
Проблема с кэшем

### ISSUE THREAD

**Issue by creative-guy** [Stanislavsky69/vue_dadata_3#27]
У меня есть 2 инпута, в одном выбирается страна, во втором, исходя из выбранной страны, выбирается город. Проблема в том, что запросы к городу(/suggest/address) кэшируются только на основе query,  не учитывают других параметров, таких как locations.

В результате, если выбираю страну Россия, а в поле город пишу букву "А", список результатов кэшируется на России. Потом меняю страну на Беларусь, в поле город снова ввожу букву "А", и получаю результаты по России, вместо результатов по Беларуси. Если ввести другую букву, не закэшированную, тогда получаю результаты для Беларуси, как и требовалось.

Поправь плз. Также, не помешала бы возможность отключать кэширование запросов.

**Comment by Stanislavsky69** [comment]
Приветствую! Принял, спасибо за обратную связь
