### ISSUE TITLE
Как сделать апгрейд с первой версии на вторую?

### ISSUE THREAD

**Issue by apasov** [Stanislavsky69/vue_dadata_3#8]
Есть ли BREAKING CHANGES?
Что нужно, чтобы проапгрейдиться так, чтобы ничего не слетело?

**Comment by Stanislavsky69** [comment]
params -> mergeParams

Подключение стилей:

@use "vue-dadata-3/styles" with (
  $dadata_v_3_base_font_size: 14px;
);

Вроде ничего не забыл ) В остальном постарался оставить функционал текущий.

По обновлению все стандартно.
